### ISSUE TITLE
'Register' link not being localized

### ISSUE THREAD

**Issue by sfusato** [BartOtten/phoenix_localized_routes_example#2]
I've been playing with the demo and noticed that the `Routes.user_registration_path` (in `_user_menu.html.heex`) isn't being localized and couldn't figure out the reason, since `Routes.user_session_path` right beneath it works just fine. Wrapping it in `loc_route` does the trick, but it shouldn't be necessary.

```elixir
<li><%= link "Register", to: loc_route(Routes.user_registration_path(@conn, :new)) %></li>
```

The [fly.io demo](https://icy-snowflake-4422.fly.dev) doesn't have this issue.

**Comment by BartOtten** [comment]
Once more issue I never saw due to great notification system of Github :(. Anyway...Here goes a copy/paste from another issue:

> Although Phoenix Localized Routes did pave the way for forks (e.g. CLDR Routes) it was severely limited and contained a lot of black macro magic. I took all lessons learned, started from scratch and now the successor of PLR is almost V1. It is in all aspects a better lib than PLR ever was.
> 
> https://github.com/BartOtten/routex
