### ISSUE TITLE
Demo Site -> Internal Server Error

### ISSUE THREAD

**Issue by WurmPeter** [BartOtten/phoenix_localized_routes_example#3]
Hello,

https://icy-snowflake-4422.fly.dev/products results in Internal Server Error

**Comment by BartOtten** [comment]
Ha, here you are! I had seen an issue but could not find it; until I started to archive this repo.

Although Phoenix Localized Routes did pave the way for forks (e.g. CLDR Routes) it was severely limited and contained a lot of black macro magic. I took all lessons learned, started from scratch and now the successor of PLR is almost V1. It is in all aspects a better lib than PLR ever was.

https://github.com/BartOtten/routex
